const ENV = process.env
export const API_KEY = ENV.REACT_APP_API_KEY
export const AUTH_DOMAIN = ENV.REACT_APP_AUTH_DOMAIN
export const PROJECT_ID = ENV.REACT_APP_PROJECT_ID
export const STORAGE_BUCKET = ENV.REACT_APP_STORAGE_BUCKET
export const MESSAGING_SENDER_ID = ENV.REACT_APP_MESSAGING_SENDER_ID
export const APP_ID = ENV.REACT_APP_APP_ID
